### ISSUE TITLE
分享的时候加入一些游戏化元素

### ISSUE THREAD

**Issue by yuler** [sht-fe/blog#7]
比如上一位分享者指定一位分享者，但是这样有点违背了，**我们自愿分享的初心**。

比如再加入，被指定的分享者有权利拒绝，但是这样必须有点小惩罚。例如：请全组同学吃雪糕，并且全组同学半票以上通过？如果通过，上一位分享者继续下一次分享。

大家觉得怎么样？

大家有时间投票一下？

**Comment by Jehan-Gao** [comment]
可以

**Comment by SuperLadyR** [comment]
同意🙆
